### ISSUE TITLE
Lifting current dependency limitation "numpy < 1.25"

### ISSUE THREAD

**Issue by desmondlzy** [NVIDIA/torch-harmonics#58]
hi thanks for the amazing work!

Just a quick question: why in`pyproject.toml`  numpy's version is set to < 1.25. Does this break anything? I'm tempted to remove this line make it work for other packages I have, just wanted to know what I might need to be extra cautious about.

**Comment by NickGeneva** [comment]
If this dependency was capped for the same reason as modulus, there was a time when pyt 2.0 was having issues with numpy versions above 1.26.

This has been since fixed. Removing the cap would be good to enable Python 3.12 installs

Relevant thread: https://github.com/NVIDIA/modulus/issues/723

**Comment by azrael417** [comment]
Hello all,

thanks for pointing that out. I think this dependency can get removed. I will prepare an MR for this right now.

Best regards
Thorsten Kurth

**Comment by azrael417** [comment]
Just fixed.
